x="ALABAMA,ALASKA,ARIZONA,ARKANSAS,CALIFORNIA,COLORADO,CONNECTICUT,DELAWARE,DC,FLORIDA,GEORGIA,HAWAII,IDAHO,ILLINOIS,INDIANA,IOWA,KANSAS,KENTUCKY,LOUISIANA,MAINE,MARYLAND,MASSACHUSETTS,MICHIGAN,MINNESOTA,MISSISSIPPI,MISSOURI,MONTANA,NEBRASKA,NEVADA,NEW-HAMPSHIRE,NEW-JERSEY,NEW-MEXICO,NEW-YORK,NORTH-CAROLINA,NORTH-DAKOTA,OHIO,OKLAHOMA,OREGON,PENNSYLVANIA,RHODE-ISLAND,SOUTH-CAROLINA,SOUTH-DAKOTA,TENNESSEE,TEXAS,UTAH,VERMONT,WASHINGTON,WEST-VIRGINIA,WISCONSIN,WYOMING"

z=x.split(",")
for i in range(10):
     print(f"<option value=\"{i+1}\">{i+1}</option>")
print(len(z))